### ISSUE TITLE
Facing Duplicate symbol error on integrating 3.0.3 camment.  

### ISSUE THREAD

**Issue by jibinmathew** [camment/sdk-ios#1]
While integrating the Camment library in react native. I am facing duplication symbol error from "UIView+Toast.h" this classes , i already have   this class in our project from another third party react native class in which we don't have ownership to change code and its having dependency in our project , Is it possible from your end to change the class name of this files to avoid duplicate symbol error. if possible its really helpful.

**Comment by alexfedosov** [comment]
@jibinmathew fixed in `3.0.4`
